exclude_paths:
  - tmp
  - vendor

detectors:
  ModuleInitialize:
    exclude:
      - Etcher
  NestedIterators:
    exclude:
      - Etcher::Builder#load
      - Etcher::Builder#transform
  TooManyStatements:
    exclude:
      - Etcher::Loaders::YAML#call
